/*
 *Read 1GB of data from the file generated by question(A)(namely,1GB_data.txt).
 */
#include<stdio.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<fcntl.h>
#include<unistd.h>
#include<time.h>
#include<stdlib.h>

unsigned long long RDTSC (void)
{
  unsigned int low, hi;
  asm volatile ("cpuid \n\t" "rdtsc \n\t": "=a" (low), "=d" (hi) ::);
  return((unsigned long long) hi << 32) | low;
}

/*
 *Too big array that cause stack overflow,
 *so I use static to define it as a global one. 
 *so it may take some seconds to compile.
 */
static int buf[1024*1024*1024/4];

int main()
{
  int filedir = open("1GB_data.txt", O_RDONLY);/*Read-Only*/

  if(filedir==-1)
    {
      perror("File cannot be opened!");
    }

  else
    {
      unsigned long int count_begin, count_end;
     
      count_begin=RDTSC(); 
      read(filedir, buf, sizeof(buf));
      count_end = RDTSC();

      printf("CPU Tick Time: %lu\n", count_end-count_begin);
    }
  
  close(filedir);

  return 0;
}
